// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCICe9mHRgnuxQU0ttpI9EipIQmVx78S1k',
    appId: '1:814165084686:web:46c0bc2f74bce582894a5f',
    messagingSenderId: '814165084686',
    projectId: 'lounge66-b8887',
    authDomain: 'lounge66-b8887.firebaseapp.com',
    storageBucket: 'lounge66-b8887.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvMnXnEcRG9hXAwtmut5d-fKgonvVYiCQ',
    appId: '1:814165084686:android:4e75c00b3b0250ad894a5f',
    messagingSenderId: '814165084686',
    projectId: 'lounge66-b8887',
    storageBucket: 'lounge66-b8887.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo7HTKy3BakueGNQ4iA_UqUF7W-qy-4LM',
    appId: '1:814165084686:ios:b57c4f5c7220736a894a5f',
    messagingSenderId: '814165084686',
    projectId: 'lounge66-b8887',
    storageBucket: 'lounge66-b8887.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo7HTKy3BakueGNQ4iA_UqUF7W-qy-4LM',
    appId: '1:814165084686:ios:4c11c81b6175e354894a5f',
    messagingSenderId: '814165084686',
    projectId: 'lounge66-b8887',
    storageBucket: 'lounge66-b8887.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
